# **Task 2 :Prediction using Decision Tree Algorithm ::**


# Author:Chaitanya Jot


importing required **library**

In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline


loading iris dataset

In [62]:
df = pd.read_csv("/content/Iris_.csv")

Getting numerical Overview Over data

In [63]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [64]:
df.tail()

Id  SepalLengthCm  ...  PetalWidthCm         Species
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[5 rows x 6 columns]

In [65]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


# Saperating X and Y

In [67]:
x = df.iloc[:,1:5]
y = df.iloc[:,5]

print('x= \n',x)
print('\n\ny=\n\n',y)

x= 
      SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]


y=

 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica


# Spliting Given Data in to Train And Test

In [68]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,
                                                 test_size = 0.3,
                                                 random_state=2021)







In [69]:
print(x_train)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
83             6.0           2.7            5.1           1.6
149            5.9           3.0            5.1           1.8
136            6.3           3.4            5.6           2.4
59             5.2           2.7            3.9           1.4
88             5.6           3.0            4.1           1.3
..             ...           ...            ...           ...
109            7.2           3.6            6.1           2.5
128            6.4           2.8            5.6           2.1
57             4.9           2.4            3.3           1.0
85             6.0           3.4            4.5           1.6
116            6.5           3.0            5.5           1.8

[105 rows x 4 columns]


In [70]:
print(y_train)

83     Iris-versicolor
149     Iris-virginica
136     Iris-virginica
59     Iris-versicolor
88     Iris-versicolor
            ...       
109     Iris-virginica
128     Iris-virginica
57     Iris-versicolor
85     Iris-versicolor
116     Iris-virginica
Name: Species, Length: 105, dtype: object


In [71]:
print(x_train.head())

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
83             6.0           2.7            5.1           1.6
149            5.9           3.0            5.1           1.8
136            6.3           3.4            5.6           2.4
59             5.2           2.7            3.9           1.4
88             5.6           3.0            4.1           1.3


In [72]:
print(y_train.head())

83     Iris-versicolor
149     Iris-virginica
136     Iris-virginica
59     Iris-versicolor
88     Iris-versicolor
Name: Species, dtype: object


# Implementing Decision Tree

In [73]:
from sklearn.tree import DecisionTreeClassifier

DTC = DecisionTreeClassifier(random_state= 2021)
DTC.fit(x_train,y_train)
print("//**** We have created the Dicision tree Classifier ****\\\\")

//**** We have created the Dicision tree Classifier ****\\


# Predicting Data

In [74]:
y_pred = DTC.predict(x_test).reshape(-1,1)
y_pred[:6]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-versicolor'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype=object)


Calculating The acuracy and Getting Confusion Matrix

In [75]:
from sklearn.metrics import accuracy_score,confusion_matrix

print("The Accuract For the Model We Created  \n\n ===>>{}".format(accuracy_score(y_pred,y_test)))
print("\n\nConfusion Matrix for the modele we Created  ==>> \n\n{}".format(confusion_matrix(y_pred,y_test)))

The Accuract For the Model We Created  

 ===>>0.9333333333333333


Confusion Matrix for the modele we Created  ==>> 

[[17  0  0]
 [ 0 16  3]
 [ 0  0  9]]
